# action.yml
name: 'Delete abandoned branches'
description: |
  Deletes old branches from your repo as long as they aren't part of an open pull request, the default branch, or protected.
author: Luis Pabon (PHPDocker.io)
branding:
  icon: git-branch
  color: orange

inputs:
  ignore_branches:
    description: "Comma-separated list of branches to ignore and never delete. You don't need to add your protected branches here."
    required: false
    default: ""
  last_commit_age_days:
    description: "How old in days must be the last commit into the branch for the branch to be deleted."
    required: false
    default: "60"
  allowed_prefixes:
    description: "Comma-separated list of prefixes a branch must match to be deleted."
    required: false
    default: ""
  dry_run:
    description: "Whether we're actually deleting branches at all. Defaults to 'yes'. Possible values: yes, no (case sensitive)"
    required: true
  github_token:
    description: "The github token to use on requests to the github api"
    required: true
  github_base_url:
    description: "The API base url to be used in requests to GitHub Enterprise"
    required: false
    default: "https://api.github.com"

outputs:
  deleted_branches: # id of output
    description: 'Branches that have been deleted, if any'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 #v4.7.1
      with:
        python-version: '3.11'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Run Action
      id: get-square
      run: python3 main.py  --ignore-branches=${{ inputs.ignore_branches }} \ 
        --last-commit-age-days=${{ inputs.last_commit_age_days }} --allowed-prefixes=${{ inputs.allowed_prefixes }} \
        --dry-run=${{ inputs.dry_run }} --github-token=${{ inputs.github_token }} \
        --github-base-url=${{ inputs.github_base_url }}
      shell: bash
